stages:
  - test
  - build
  - release

variables:
  DOCKER_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}"  # Имя Docker-образа

Django Tests:
  stage: test 
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python manage.py test --noinput
  tags:
    - docker

Build Docker Image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  tags:
    - docker  

Release Docker Image:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker tag $DOCKER_IMAGE "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
    - docker push "${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  when: manual  # Запуск вручную
  tags:
    - docker